<?php

if( !defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Verify Token calculated by user.
 *
 * @param string $token The token generated by the user.
 * @return bool The result of logical operations with google api's response.
 */

function verifyGuestCaptcha($token){
	include_once TRIPLE_A_SENSEI_PATH . 'includes/db-api.php';
	$secret = Triple_A_Sensei_DB_API::get_value('cap-secret-key');
	$response = wp_remote_post("https://www.google.com/recaptcha/api/siteverify", [
		'body' => [
			'secret'   => $secret,
			'response' => $token,
			'remoteip' => $_SERVER['REMOTE_ADDR']
		]
	]);

	if(is_wp_error($response)){
		return false;
	}

	$data = json_decode(wp_remote_retrieve_body($response), true);
	
	if (empty($data['success']) || $data['success'] !== true) {
		return false;
	}

	
	error_log("Score reCaptchav3: {$data['score']}");
	return isset($data['score']) && $data['score'] >= 0.7;
	//return !empty($data['success']) && $data['success'] === true;
}